# Generated by Django 3.2.12 on 2022-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_hands_app', '0002_donation_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'fundation'), (2, 'non-governmental organization '), (3, 'lokal collection')], default=1),
        ),
    ]
