# Generated by Django 3.2.12 on 2022-04-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_hands_app', '0003_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.DateField(),
        ),
    ]
